version: 2
updates:
  - package-ecosystem: "github-actions"  # Checks for updates in GitHub Actions workflows
    directory: "/"  # Root directory
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"  # Checks for updates in Gradle dependencies
    directory: "/"  # Root directory
    schedule:
      interval: "daily"
