name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev  # Add more branches if needed
  pull_request:
    branches:
      - main
      - dev  # Run CI on pull requests as well
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use Java 17 LTS for stability
          distribution: 'temurin'

      - name: Verify Java Version
        run: java -version
        shell: cmd

      - name: Build the project
        run: .\gradlew.bat build
        shell: cmd

      - name: Run tests
        run: .\gradlew.bat test
        shell: cmd
