jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle (Optional)
        run: chmod +x gradlew.bat
        shell: bash

      - name: Build the project
        run: gradlew.bat build
        shell: cmd

      - name: Run tests
        run: gradlew.bat test
        shell: cmd
